version: "3.8"


services:

  mongodb:
    container_name: mongodb
    image: mongo:8.0.3
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongodb:/data/db
    networks:
      - external_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/"
      ME_CONFIG_BASICAUTH: false

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    networks:
      - external_network
    env_file:
      - ./app/.env.dev
    restart: always
    environment: # The keys are required to access the AWS SECERT MANAGER (export them in the machine)
      - USER_AGENT=qutaiba
    command: /bin/sh -c "echo 'Running start_app.sh' && /app/start_app.sh"

networks:
  external_network:
    external: true