version: "3.8"


services:

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    networks:
      - external_network
    env_file:
      - ./.env.dev
    restart: always
    environment: # The keys are required to access the AWS SECERT MANAGER (export them in the machine)
      - USER_AGENT=qutaiba
    command: /bin/sh -c "echo 'Running start_app.sh' && /app/start_app.sh"

networks:
  external_network:
    external: true
